//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public byte StatusId { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public System.Guid ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
    }
}
